{"name": "test_div[negativenum]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -2 == 1.0", "trace": "self = <test_calcutor.TestCalc object at 0x0000000003CDF370>\nget_instance = <pythoncode.Calculator.Calculator object at 0x0000000003D4BA00>\nget_datas_with_fixture = [-1, -1, -2]\n\n    def test_div(self,get_instance, get_datas_with_fixture):\n    \n        f = get_datas_with_fixture\n    \n        try:\n>           assert f[2] == get_instance.div(f[0],f[1])\nE           assert -2 == 1.0\n\ntest_calcutor.py:77: AssertionError"}, "attachments": [{"name": "stdout", "source": "df4d9e7c-cea7-4a1a-9400-2359def05f3d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_datas_with_fixture", "value": "[-1, -1, -2]"}], "start": 1615198034980, "stop": 1615198034981, "uuid": "4e2cb0a2-bd12-4322-80bd-4da28410da3c", "historyId": "7bac213d2abb355779590c25e599539a", "testCaseId": "42d6b15ebfef6dc8ff0705bb87b06251", "fullName": "test_calcutor.TestCalc#test_div", "labels": [{"name": "suite", "value": "test_calcutor"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "ZX-201601031503"}, {"name": "thread", "value": "2260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calcutor"}]}